databases:
  - name: dummy_django_blog_on_render
    user: admin
    plan: free
    region: frankfurt

services:
  - type: web
    name: dummy_django_blog_on_render
    plan: free
    region: frankfurt
    runtime: python
    buildCommand: "./docker-compose-deployment.sh cloud"
    startCommand: "./venv/bin/python -m gunicorn -b :8000 dummy_django_blog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dummy_django_blog_on_render
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: POETRY_VERSION
        value: 1.8.3
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_LOGIN
        value: admin
      - key: DJANGO_ADMIN_PASSWORD
        generateValue: true
      - key: DJANGO_ADMIN_EMAIL
        value: admin@bluelake.fr
