# Generated by Django 5.1 on 2024-08-15 02:04

import blog.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contribution", models.CharField(blank=True, max_length=250)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_photo",
                    models.CharField(max_length=125, verbose_name="titre photo"),
                ),
                ("caption", models.CharField(max_length=350, verbose_name="legende")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", models.ImageField(upload_to="", verbose_name="photo")),
                ("starred", models.BooleanField(default=False)),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("add_multiple_photos", "Peut ajouter plusieurs photos")
                ],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[blog.validators.MustContainsDigit()],
                        verbose_name="titre billet",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content",
                    models.CharField(max_length=2500, verbose_name="description"),
                ),
                ("starred", models.BooleanField(default=False)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "contributors",
                    models.ManyToManyField(
                        related_name="contributions",
                        through="blog.Contributor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        default="assets/img/les_petits_meurtres_la_fin.png",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.photo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contributor",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("contributor", "post")},
        ),
    ]
