# Generated by Django 4.2.14 on 2024-07-19 05:53

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=200, validators=[blog.validators.MustContainsSpecialChar]
            ),
        ),
    ]
