# Generated by Django 4.2.14 on 2024-07-19 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_photo_uploader"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
