# Generated by Django 4.2.14 on 2024-07-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_word_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "permissions": [
                    ("add_multiple_photos", "Peut ajouter plusieurs photos")
                ]
            },
        ),
    ]
