# Generated by Django 4.2.14 on 2024-07-19 19:02

from django.db import migrations, models
import blog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_photo_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[blog.validators.MustContainsSpecialChar()],
            ),
        ),
    ]
