# Generated by Django 4.2.14 on 2024-07-19 20:32

from django.db import migrations

def replace_single_author_by_contributors(apps, schema_editor):
    Post = apps.get_model("blog", "Post")

    for post in Post.objects.all():
        if post.author:
            post.contributors.add(post.author, through_default={"contribution": "Auteur principal"})

class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_post_author_contributor_post_contributors"),
    ]
    
    operations = [
        migrations.RunPython(replace_single_author_by_contributors)
    ]
