# Generated by Django 4.2.14 on 2024-07-19 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0009_auto_20240719_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contributors",
            field=models.ManyToManyField(
                related_name="contributions",
                through="blog.Contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
