# Generated by Django 4.2.14 on 2024-07-21 19:16

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_contributors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="caption",
            field=models.CharField(max_length=350, verbose_name="legende"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="photo"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(max_length=125, verbose_name="titre photo"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=2500, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[blog.validators.MustContainsSpecialChar()],
                verbose_name="titre billet",
            ),
        ),
    ]
