# Generated by Django 4.2.14 on 2024-07-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_photo_caption_alter_photo_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="title",
            new_name="title_photo",
        ),
    ]
