# Generated by Django 4.2.14 on 2024-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_rename_title_photo_title_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
